### ISSUE TITLE
Dataset for training

### ISSUE THREAD

**Issue by manosh7n** [Eric-Canas/qrdet#1]
Model works very well for my tasks. 
What dataset did you use to train your yolo model?

**Comment by Eric-Canas** [comment]
Hi @manosh7n!

I merged every single open source dataset I could find in the [roboflow universe](https://universe.roboflow.com/) that was related with _QRs_. Then I cleaned all them up from some classes I didn't need (such as barcodes), cases that were extremely difficult to see for the human eye or miss-labeled images. Next, I did some semi-automatic data augmentation in order to change the base color of some _QRs_. And finally, I added some negative images for cases I thought that could be easily confused with _QRs_, such as car plates.

**Comment by rusmux** [comment]
Is it possible to find this dataset somewhere, or is it private?

**Comment by Eric-Canas** [comment]
Hi! Send me a mail to eric@ericcanas.com

**Comment by Mechazo11** [comment]
Hi @Eric-Canas thank you for making `qrdet` publicly available. I too am curious about the dataset since I wanted to use YOLOv11 model to do just QR code detection using your library. Have you made the dataset publicly available yet?

Best,
@Mechazo11
