### ISSUE TITLE
`_WEIGHTS_FOLDER` is not always writable

### ISSUE THREAD

**Issue by sam-30** [Eric-Canas/qrdet#11]
If this library is run in an AWS Lambda function, the currently hardcoded `_WEIGHTS_FOLDER` (`.model`) is not writable, as [AWS only allows write access to the `/tmp` folder](https://repost.aws/questions/QUoCCNNS59RryAKeEBezXFcg/how-to-work-around-directory-permissions-in-aws-lambda).

*Possible Solution*
Add a new parameter (e.g. `dir_for_downloads`) to the `QRDetector.__init__` function with a default value of `None`.  If the parameter is not `None`, update the `_WEIGHTS_FOLDER` with the new directory name.

*Notes for Reviewers*
Not sure of the best python pattern (not sure globals like `_WEIGHTS_FOLDER` should be updated like I'm proposing), but the end goal is to allow the caller to control the folder where the weights get downloaded so that AWS Lambda functions can pass in `/tmp`.

**Comment by Eric-Canas** [comment]
Hi! 

Thanks for the proposed solution!

Best pattern would be to pass it as a parameter in the init and populate it. But setting the `_WEIGHTS_FOLDER` as default value.

This would allow the user to select a different folder. I'm not sure right now if it would have any undesired implication. But I guess it wouldn't.



Thanks again! I would really want to get some time to do various updates in this library, but things are getting hard at my workplace and it is getting really hard to find that time.

I'll review any pull request!

**Comment by sam-30** [comment]
> I'll review any pull request!

Do you need to add me as a contributor in order to push a branch up and create a PR?  I have a branch ready for review.

**Comment by sam-30** [comment]
I also wanted to see what you thought about using `[tempfile](https://docs.python.org/3/library/tempfile.html)` to spin up a temp directory, download the weights, do the processing then allow `tempfile` to handle clean up.  This library also plays nicely with AWS.

**Comment by Eric-Canas** [comment]
Hi! 

I think you should be able to do a pull request without problems if you are forked. Qreader has received [some PRs](https://github.com/Eric-Canas/QReader/pulls?q=is%3Apr+is%3Aclosed) without any problem.

About [tempfile](https://docs.python.org/3/library/tempfile.html), I don't think it would be a good idea, as it would make the library connection-dependent, breaking some projects that are using it in embedded systems. 

Currently, it downloads the model and saves it locally, so you only need internet the first time you need to use the model. The `_WEIGHTS_FOLDER`points inside the library folder, so uninstalling the library would also remove the weights which I guess is the expected behavior.

In fact... I think that executing a test before uploading the Lambda layer, should actually force the model download and save the weights within the layer folder. So they could be preloaded in the layer. But anyway, layers have a maximum size and being able to download them to `/tmp` folder or, in fact, whichever the user wants, is probably a better solution.

**Comment by pibahamondesw** [comment]
@sam-30 I reached this exact same problem today when trying to create a Lambda function on AWS (that essentially preprocess an image and tries to retrieve the content of a QRCode on it). I see that there is no parameter to replace the _WEIGHTS_FOLDER yet. Were you able to fix it on your side? I'd appreciate any help here. 🙏

**Comment by sam-30** [comment]
> @sam-30 I reached this exact same problem today when trying to create a Lambda function on AWS (that essentially preprocess an image and tries to retrieve the content of a QRCode on it). I see that there is no parameter to replace the _WEIGHTS_FOLDER yet. Were you able to fix it on your side? I'd appreciate any help here. 🙏

I overwrote  the `_WEIGHTS_FOLDER` by importing it into my app and pushed the pre-downloaded into a /temp folder that was accessible.  Still haven't gotten to a proper PR.

**Comment by Eric-Canas** [comment]
Hi!

I just deployed the solution. Now when you [instantiate QRDetector()](https://github.com/Eric-Canas/qrdet?tab=readme-ov-file#qrdetectormodel_size--s-conf_th--05-nms_iou--03-weights_folder--qrdet_packagemodel), there is a new parameter called `weights_folder` for modifying the downloading path. If you need to download the weights to a different folder, you can just `QRDetector(weights_folder='/tmp')`

That's already available in [PyPi](https://pypi.org/project/qrdet/), you can update it by

`pip install --upgrade qrdet`

**Comment by sam-30** [comment]
> Hi!
> 
> I just deployed the solution. Now when you [instantiate QRDetector()](https://github.com/Eric-Canas/qrdet?tab=readme-ov-file#qrdetectormodel_size--s-conf_th--05-nms_iou--03-weights_folder--qrdet_packagemodel), there is a new parameter called `weights_folder` for modifying the downloading path. If you need to download the weights to a different folder, you can just `QRDetector(weights_folder='/tmp')`
> 
> That's already available in [PyPi](https://pypi.org/project/qrdet/), you can update it by
> 
> `pip install --upgrade qrdet`

Just saw this, since I was running on my sloppy hack.  Will be using this solution going forward!
